theme: minima
title: Creative Director, Sales Executive
author: Devon
email: dmikhailcevatli@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here is the professional blog and living resume of Devon

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  dmikcev
show_excerpts: true # set to false to remove excerpts on the homepage
